name: factory_app
description: A new Flutter project for a factory application.

publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  video_player: ^2.9.1
  firebase_auth: ^5.1.2
  introduction_screen: ^3.0.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.3
  firebase_storage: ^12.1.1
  flutter_local_notifications: ^17.2.1+2
  cloud_firestore: ^5.1.0
  provider: ^6.0.5
  flutter_hooks: ^0.20.5
  uuid: ^4.4.0
  firebase_core: ^3.2.0
  shared_preferences: ^2.0.13
  cloud_functions: ^5.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  permission_handler: ^11.3.1
  flutter_pdfview: ^1.3.2
  pdf: ^3.11.0
  syncfusion_flutter_pdfviewer: ^26.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.4.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/ShuwayerLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets\EES Company Profile..pdf
    - assets/placeholder.png
    - assets/ShuwayerLogo.png
    - assets/Shuwayer.mp4
    - assets/about1.jpg
    - assets/about2.jpg
    - assets/about3.jpg
    - assets/company1.png
    - assets/company2.png
    - assets/company3.png
    - assets/company4.png
    - assets/company5.png
    - assets/company6.png
    - assets/intro1.png
    - assets/intro2.png
    - assets/lang/
    - lib/l10n/intl_en.json
    - lib/l10n/intl_ar.json

