// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOSVGKbtOSFivABOKB_rzFydv7wyuK5I',
    appId: '1:335964168926:web:cb35da016c25006a96984f',
    messagingSenderId: '335964168926',
    projectId: 'factoryapp-7775e',
    authDomain: 'factoryapp-7775e.firebaseapp.com',
    databaseURL: 'https://factoryapp-7775e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-7775e.appspot.com',
    measurementId: 'G-1J2WNY8LZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7VUN2_8YhY-yImw_7FJLEInbGy4RQ0j8',
    appId: '1:335964168926:android:77e209098788085d96984f',
    messagingSenderId: '335964168926',
    projectId: 'factoryapp-7775e',
    databaseURL: 'https://factoryapp-7775e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-7775e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EVxU9u4eBdybp1GC8gLKcMhL86NUhAw',
    appId: '1:335964168926:ios:1dc628d6ffac82dc96984f',
    messagingSenderId: '335964168926',
    projectId: 'factoryapp-7775e',
    databaseURL: 'https://factoryapp-7775e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-7775e.appspot.com',
    iosBundleId: 'com.example.factoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EVxU9u4eBdybp1GC8gLKcMhL86NUhAw',
    appId: '1:335964168926:ios:1dc628d6ffac82dc96984f',
    messagingSenderId: '335964168926',
    projectId: 'factoryapp-7775e',
    databaseURL: 'https://factoryapp-7775e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-7775e.appspot.com',
    iosBundleId: 'com.example.factoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLOSVGKbtOSFivABOKB_rzFydv7wyuK5I',
    appId: '1:335964168926:web:8a532f467388caa796984f',
    messagingSenderId: '335964168926',
    projectId: 'factoryapp-7775e',
    authDomain: 'factoryapp-7775e.firebaseapp.com',
    databaseURL: 'https://factoryapp-7775e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-7775e.appspot.com',
    measurementId: 'G-BPN2VHB1T6',
  );

}